"""add text_content to documents

Revision ID: 7d268e57e751
Revises: 3fec1f7ff684
Create Date: 2026-07-21 11:39:47.670917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d268e57e751'
down_revision: Union[str, Sequence[str], None] = '3fec1f7ff684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('text_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'text_content')
    # ### end Alembic commands ###
